### ISSUE TITLE
[INTRO] 

### ISSUE THREAD

**Issue by alaamjadi** [planetlabs-community/planet-hack-2020#22]
_Hi, my name is:_ Mohammad
_my pronouns are:_ He/Him/His

------

**What I bring to a hack team (skills, experience, interest, etc):**
I am a telecommunication student focusing on cybersecurity. I have experience with IoT, cloud, Python, and javascript.

**What kind of project I'd like to work on:**
A project focused on security which monitors, protects, investigates, and prevents natural and unnatural disasters that may affect our planet on a global scale.

**Why am I leaving this Hackathon?**
Till now I did not get the clearance from the legal compliance team and they told me they are unable to provide further information. Being an Iranian is painful because you will be boycotted by your own country and then other countries! I hope this will change soon!

**Comment by sarasafavi** [comment]
We're sorry you were unable to participate in this hackathon. Unfortunately, your registration was not received in time for the manual review process to be completed in order to create a new account for you. This process is mandatory and was applied to all hackathon participants regardless of country of origin. After receiving your registration we attempted to rush this process in order to allow you to participate anyway but ultimately we were unable to create an account for you before the hackathon began.
